### ISSUE TITLE
Deleting a video from playlist results in Connection Timed Out

### ISSUE THREAD

**Issue by kmccmk9** [darkhz/invidtui#26] opened 2023-06-26 20:54 UTC
Hi! As the title implies, trying to remove a video from a playlist results in a "Connection Timed Out" error. Upon reviewing the code and comparing it to the invidious API, I don't believe there is anything weird happening where it is waiting for a large message body to be returned. According to the API it should return a successful code and no body. I've tried this against two instances and the same behavior is exhibited on both. Could this be a token scope issue? I noticed if you follow the token approach rather than the session approach it explicitly lists only GET permissions. I'm not too familiar with the session method's underlying methods. If the session token is supposed to be representative of the fully logged in browser session along with all it's expected permissions than I should raise this issue against invidious itself? If there is only a guaranteed set of read-only permissions given to the session ID similar to the token method, is there a way for us to expand the requested scopes, to include modification of objects such as playlists? From the code itself, I don't see any explicit scopes being requested when using the session token.

**Comment by darkhz** [comment] 2023-06-30 21:52
Can you check again with the new version? I am able to delete videos (as demonstrated in the video within the README) and it does not show the time out error.

**Comment by kmccmk9** [comment] 2023-07-04 00:16
Ok I did try again and this time it says "Delete: <url>: EOF". So I'm guessing there is a problem with the response from that API call?

**Comment by darkhz** [comment] 2023-07-04 01:41
@kmccmk9 yes it probably is an API issue. What is the instance you are using? I'd like to look into it as well.

**Comment by kmccmk9** [comment] 2023-07-04 02:51
Sure no problem. What else can I do to help track down this problem? I could spend some time sending requests from postman to see if I can reproduce there as well. 

The instance I've been testing against is [Puffyan](https://vid.puffyan.us/feed/subscriptions)

**Comment by darkhz** [comment] 2023-07-04 06:26
@kmccmk9  Ok, I have tested it with puffyan right now, and I'm getting the same error. But when I try with [protokolla](https://invidious.protokolla.fi), the error does not occur and the video gets deleted. Maybe it is an instance issue?

**Comment by darkhz** [comment] 2023-08-02 07:38
@kmccmk9 hello again, this issue is confirmed to be related to the particular instance, since instance administrators may disable certain endpoints/features. Changing the instance should work. I am closing this issue for now, but feel free to re-open this if the issue persists.

**Closed as completed** 2023-08-02 07:39 UTC
